version: '3'

services:
   db:
     image: mysql:5.7
     command: --character-set-server=utf8 --collation-server=utf8_general_ci 
     ports:
       - "3306:3306"
     environment:
      MYSQL_DATABASE: factlist
      MYSQL_ROOT_PASSWORD: factlist
     restart: always
   api:
     depends_on:
       - db
     image: factlist/factlist-api
     ports:
       - "8000:8000"
     restart: always
     environment:
      DB_HOST: "db"
      DB_NAME: "factlist"
      DB_USERNAME: "root"
      DB_PASSWORD: "factlist"
      DB_PORT: 3306
      DJANGO_SECRET_KEY: "secret"
      DJANGO_SETTINGS_MODULE: "factlist.settings.dev"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_STORAGE_BUCKET_NAME: ""
   ui:
     depends_on:
       - api
     image: factlist/factlist-ui
     ports:
       - "3000:3000"
     restart: always
   redis:
    image: redis:latest
