version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./data/seed.sql:/docker-entrypoint-initdb.d/seed.sql
     environment:
      MYSQL_DATABASE: factlist
      MYSQL_ROOT_PASSWORD: factlist
     restart: always
   api:
     depends_on:
       - db
     image: factlist/factlist-api
     ports:
       - "8884:8884"
     restart: always
     environment:
      DB_HOST: "db"
      DB_NAME: "factlist"
      DB_USERNAME: "root"
      DB_PASSWORD: "factlist"
      DB_PORT:  3306
      PORT:  8884
      JWT_SIGNING_KEY: "YOUR_SIGNING_KEY"
      ACCESS_KEY_ID: ""
      SECRET_KEY: ""
      S3_REGION: ""
      S3_BUCKET: ""
   ui:
     depends_on:
       - api
     image: factlist/factlist-ui
     ports:
       - "3000:3000"
     restart: always